version: '3.8'

services:
  postgres_auth_lis:
    container_name: postgres_auth_lis
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5447:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: